[package]
name = "Exokernel"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[workspace]
members = [
    # x86_64 BIOS Bootloader
    "kernel/arch/x86_64/bootloader/bios",
    "kernel/arch/x86_64/bootloader/bios/stage-1"
]

[dependencies]
x86_64-bootloader-bios = { path = "kernel/arch/x86_64/bootloader/bios", artifact = "bin", target = "x86_64-unknown-none" }