[package]
name = "exokernel"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[workspace]
members = [
    # File system
    "lib/fs",

    # x86_64 BIOS Bootloader
    "kernel/arch/x86_64/bootloader/bios",
    "kernel/arch/x86_64/bootloader/bios/stage-1",
    "kernel/arch/x86_64/bootloader/bios/stage-2",

    # Build utils
    "lib/bios-util"
]

[build-dependencies]
llvm-tools = "0.1.1"

bios-util = { path = "lib/bios-util" }
fs = { path = "lib/fs", features = [ "std" ] }