[package]
name = "x86_64-bootloader-bios-stage-2"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
# fs = { path = "../../../../../../lib/fs", default-features = false, features = ["kernel"] }
