[package]
name = "x86_64-bootloader-bios"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[build-dependencies]
[build-dependencies.x86_64-bootloader-bios-stage-1]
path = "stage-1"
artifact = "bin"

[build-dependencies.x86_64-bootloader-bios-stage-2]
path = "stage-2"
artifact = "bin"